//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymPrimerParcialWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int id_emp { get; set; }
        public string contrasena_emp { get; set; }
        public string num_emp { get; set; }
        public Nullable<int> id_usu { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
