//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymPrimerParcialWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.empleado = new HashSet<empleado>();
            this.membresia = new HashSet<membresia>();
            this.tarjeta = new HashSet<tarjeta>();
        }
    
        public int id_usuario { get; set; }
        public string nombre_usu { get; set; }
        public string apellido_pat_usu { get; set; }
        public string apellido_mat_usu { get; set; }
        public string genero_usu { get; set; }
        public System.DateTime fecha_nac_usu { get; set; }
        public string telefono_usu { get; set; }
        public string correo_usu { get; set; }
        public Nullable<int> id_domicilio { get; set; }
    
        public virtual domicilio domicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membresia> membresia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarjeta> tarjeta { get; set; }
    }
}
